#!/usr/bin/env node

/* eslint-disable no-template-curly-in-string */

let _ = require('lodash-y');

let deploycJobsMinimal = require('./deployc-jobs-minimal');
let deploycJobsCommon = require('./deployc-jobs-common');

// -----------------------------------------------------------------------------

let workflow = {
  name: '20. CD container',
  on: {
    push: {
      tags: [
        'v*'
      ]
    }
  },
  concurrency: {
    group: 'deployc-${{ github.ref }}'
    // 'cancel-in-progress': false
  },
  jobs: {
    ...deploycJobsMinimal,
    ...deploycJobsCommon
  }
};

if (require.main === module) {
  // eslint-disable-next-line no-console, no-null/no-null
  console.log(JSON.stringify(workflow, null, 2));
} else {
  module.exports = workflow;
}
