#!/usr/bin/env node

/* eslint-disable no-template-curly-in-string */

let _ = require('lodash-y');

let maincJobsMinimal = require('./mainc-jobs-minimal');
let maincsJobsCommon = require('./mainc-jobs-common');

// -----------------------------------------------------------------------------

let workflow = {
  name: '11. CI container',
  on: {
    push: {
      branches: [
        'github*'
        // 'master'
      ]
    },
    pull_request: {
      branches: [
        '**'
      ]
    },
    schedule: [{
      cron: '0 0 * * *'
    }],
    // eslint-disable-next-line no-null/no-null
    workflow_dispatch: null
  },
  concurrency: {
    group: 'mainc-${{ github.ref }}',
    'cancel-in-progress': true
  },
  jobs: {
    ...maincJobsMinimal,
    ...maincsJobsCommon
  }
};

// NOTE PLACEHOLDER FOR DEBUG PURPOSES
/*
workflow.jobs = _.mapValues(_.pick(workflow.jobs, [
  'main-windows'
]), function(job) {
  return _.omit(job, [
    'needs'
  ]);
});
*/

if (require.main === module) {
  // eslint-disable-next-line no-console, no-null/no-null
  console.log(JSON.stringify(workflow, null, 2));
} else {
  module.exports = workflow;
}
