#!/usr/bin/env node

let _ = require('lodash-firecloud');

let jobs = require('./main-jobs');
let containerJobs = require('./main-container-jobs');

// -----------------------------------------------------------------------------

let on = {};
on.push = {
  branches: [
    'github*',
    'master'
  ],
  tags: [
    'v*'
  ]
};
on.pull_request = {
  branches: [
    '**'
  ]
};
on.schedule = [{
  cron: '0 0 * * *'
}];
// eslint-disable-next-line no-null/no-null
on.workflow_dispatch = null;

// -----------------------------------------------------------------------------


// -----------------------------------------------------------------------------

let workflow = {
  name: 'CI',
  on,
  jobs: {
    ...jobs,
    ...containerJobs
  }
};

// eslint-disable-next-line no-console, no-null/no-null
console.log(JSON.stringify(workflow, null, 2));
