#!/usr/bin/env node

/* eslint-disable no-template-curly-in-string */

let _ = require('lodash-firecloud');

let jobs = require('./main-jobs');
let maincJobs = require('./main-mainc-jobs');
let deploycMinimalJobs = require('./main-deployc-minimal-jobs');
let deploycCommonJobs = require('./main-deployc-common-jobs');

// -----------------------------------------------------------------------------

let workflow = {
  name: 'CI',
  on: {
    push: {
      branches: [
        'github*',
        'master'
      ],
      tags: [
        'v*'
      ]
    },
    pull_request: {
      branches: [
        '**'
      ]
    },
    schedule: [{
      cron: '0 0 * * *'
    }],
    // eslint-disable-next-line no-null/no-null
    workflow_dispatch: null
  },
  concurrency: {
    group: '${{ github.ref }}',
    'cancel-in-progress': true
  },
  jobs: {
    ...jobs,
    ...maincJobs,
    ...deploycMinimalJobs,
    ...deploycCommonJobs
  }
};

// eslint-disable-next-line no-console, no-null/no-null
console.log(JSON.stringify(workflow, null, 2));
