#!/usr/bin/env node

let _ = require('lodash-firecloud');

let jobs = require('./main-jobs');
let containerJobs = require('./main-container-jobs');

// -----------------------------------------------------------------------------

let workflow = {
  name: 'CI',
  on: {
    push: {
      branches: [
        'github*',
        'master'
      ],
      tags: [
        'v*'
      ]
    },
    pull_request: {
      branches: [
        '**'
      ]
    },
    schedule: [{
      cron: '0 0 * * *'
    }],
    // eslint-disable-next-line no-null/no-null
    workflow_dispatch: null
  },
  jobs: {
    ...jobs,
    ...containerJobs
  }
};

// eslint-disable-next-line no-console, no-null/no-null
console.log(JSON.stringify(workflow, null, 2));
