image: 'ysoftwareab/yp-ubuntu-20.04-common:latest'
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
vscode:
  extensions:
    - cardinal90.multi-cursor-case-preserve
    - chrislajoie.vscode-modelines
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.editorconfig
    - glen-84.sass-lint
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
    - orta.vscode-jest
    - timonwong.shellcheck
tasks:
  - command: |-
      source sh/dev.inc.sh
      gp env PATH=$PATH
      gp open README.md
      make help

