variables:
  FORCE_UNSAFE_CONFIGURE: "1"
  GIT_SUBMODULE_STRATEGY: recursive
  YP_CI_BREW_INSTALL: minimal
  YP_LOG_BOOTSTRAP: "true"

.aliases:
  - &shared
    image:
      # name: ubuntu:20.04
      # NOTE using the prebuilt docker image of homebrew (linuxbrew)
      # because homebrew cannot be installed as root,
      # and creating a sudoer user and then running gitlab jobs through it failed
      name: homebrew/ubuntu20.04:3.2.8
    only:
      - /^gitlab/ # gitlab branches
      # - master
      # - /^v(\d+)\.(\d+)\.(\d+)/ # version tags
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        # common
        - $HOME/.local
        - $HOME/.npm
        # macos
        - $HOME/.homebrew
        - $HOME/Library/Caches/Homebrew
        - $HOME/Library/Caches/pip
        # linux
        - $HOME/.cache/Homebrew
        - $HOME/.cache/pip
        - $HOME/.linuxbrew


main_job:
  <<: *shared
  script:
    - |
      set -x
      sudo chown -R $(id -u):$(id -g) ${CI_PROJECT_DIR}
    - |
      set -euo pipefail
      cd ${CI_PROJECT_DIR}
      source ci/pipeline.script.sh
