image: 'ysoftwareab/yp-ubuntu-20.04-common:latest'
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
vscode:
  extensions:
    - bierner.github-markdown-preview
    - cardinal90.multi-cursor-case-preserve
    - chrislajoie.vscode-modelines
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.editorconfig
    - fnando.linter
    - glen-84.sass-lint
    - hashicorp.terraform
    - mads-hartmann.bash-ide-vscode
    - me-dutour-mathieu.vscode-github-actions
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
    - ms-vscode.makefile-tools
    - redhat.vscode-yaml
    - orta.vscode-jest
    - timonwong.shellcheck
tasks:
  - command: |-
      source sh/dev.inc.sh
      gp env PATH=$PATH
      gp open README.md
      make help

