# https://github.com/editorconfig-checker/editorconfig-checker
YP_ECCHECKER_VSN=2.4.0

# https://github.com/stedolan/jq
YP_JQ_VSN=1.6

# https://github.com/josephburnett/jd
YP_JD_VSN=1.5.0

# https://github.com/zricethezav/gitleaks
YP_GITLEAKS_VSN=8.2.4

# https://github.com/github/gitignore
YP_GITHUB_GITIGNORE_VSN=96d68766538413194aabd55e3622734cd501e715

# https://github.com/sgerrand/alpine-pkg-glibc
YP_ALPINE_PKG_GLIBC_VSN=2.32-r0

# https://github.com/mikefarah/yq
YP_YQ_VSN=4.16.2

# https://github.com/ysoftwareab/nanoseconds
YP_NANOSECONDS_VSN=0.0.1
