# the g-prefixed commands are supposed to cater for MacOS (i.e. homebrew, etc)

# coreutils: generated by
# ls $(brew --prefix coreutils)/libexec/gnubin | grep -v '^\[$' | while read -r VAR; do VAR_UPPER="$(echo "$VAR" | tr "[:lower:]" "[:upper:]")"; echo "$VAR_UPPER = \$(call which,${VAR_UPPER},g$VAR $VAR)"; done # editorconfig-checker-disable-line

B2SUM = $(call which,B2SUM,gb2sum b2sum)
BASE32 = $(call which,BASE32,gbase32 base32)
BASE64 = $(call which,BASE64,gbase64 base64)
BASENAME = $(call which,BASENAME,gbasename basename)
BASENC = $(call which,BASENC,gbasenc basenc)
CAT = $(call which,CAT,gcat cat)
CHCON = $(call which,CHCON,gchcon chcon)
CHGRP = $(call which,CHGRP,gchgrp chgrp)
CHMOD = $(call which,CHMOD,gchmod chmod)
CHOWN = $(call which,CHOWN,gchown chown)
CHROOT = $(call which,CHROOT,gchroot chroot)
CKSUM = $(call which,CKSUM,gcksum cksum)
COMM = $(call which,COMM,gcomm comm)
CP = $(call which,CP,gcp cp)
CSPLIT = $(call which,CSPLIT,gcsplit csplit)
CUT = $(call which,CUT,gcut cut)
DATE = $(call which,DATE,gdate date)
DD = $(call which,DD,gdd dd)
DF = $(call which,DF,gdf df)
DIR = $(call which,DIR,gdir dir)
DIRCOLORS = $(call which,DIRCOLORS,gdircolors dircolors)
DIRNAME = $(call which,DIRNAME,gdirname dirname)
DU = $(call which,DU,gdu du)
ECHO = $(call which,ECHO,gecho echo)
ENV = $(call which,ENV,genv env)
EXPAND = $(call which,EXPAND,gexpand expand)
EXPR = $(call which,EXPR,gexpr expr)
FACTOR = $(call which,FACTOR,gfactor factor)
FALSE = $(call which,FALSE,gfalse false)
FMT = $(call which,FMT,gfmt fmt)
FOLD = $(call which,FOLD,gfold fold)
GROUPS = $(call which,GROUPS,ggroups groups)
HEAD = $(call which,HEAD,ghead head)
HOSTID = $(call which,HOSTID,ghostid hostid)
ID = $(call which,ID,gid id)
INSTALL = $(call which,INSTALL,ginstall install)
JOIN = $(call which,JOIN,gjoin join)
KILL = $(call which,KILL,gkill kill)
LINK = $(call which,LINK,glink link)
LN = $(call which,LN,gln ln)
LS = $(call which,LS,gls ls)
MD5SUM = $(call which,MD5SUM,gmd5sum md5sum)
MKDIR = $(call which,MKDIR,gmkdir mkdir)
MKFIFO = $(call which,MKFIFO,gmkfifo mkfifo)
MKNOD = $(call which,MKNOD,gmknod mknod)
MKTEMP = $(call which,MKTEMP,gmktemp mktemp)
MV = $(call which,MV,gmv mv)
NICE = $(call which,NICE,gnice nice)
NL = $(call which,NL,gnl nl)
NOHUP = $(call which,NOHUP,gnohup nohup)
NPROC = $(call which,NPROC,gnproc nproc)
NUMFMT = $(call which,NUMFMT,gnumfmt numfmt)
OD = $(call which,OD,god od)
PASTE = $(call which,PASTE,gpaste paste)
PATHCHK = $(call which,PATHCHK,gpathchk pathchk)
PINKY = $(call which,PINKY,gpinky pinky)
PR = $(call which,PR,gpr pr)
PRINTENV = $(call which,PRINTENV,gprintenv printenv)
PRINTF = $(call which,PRINTF,gprintf printf)
PTX = $(call which,PTX,gptx ptx)
READLINK = $(call which,READLINK,greadlink readlink)
REALPATH = $(call which,REALPATH,grealpath realpath)
RM = $(call which,RM,grm rm)
RMDIR = $(call which,RMDIR,grmdir rmdir)
RUNCON = $(call which,RUNCON,gruncon runcon)
SEQ = $(call which,SEQ,gseq seq)
SHA1SUM = $(call which,SHA1SUM,gsha1sum sha1sum)
SHA224SUM = $(call which,SHA224SUM,gsha224sum sha224sum)
SHA256SUM = $(call which,SHA256SUM,gsha256sum sha256sum)
SHA384SUM = $(call which,SHA384SUM,gsha384sum sha384sum)
SHA512SUM = $(call which,SHA512SUM,gsha512sum sha512sum)
SHRED = $(call which,SHRED,gshred shred)
SHUF = $(call which,SHUF,gshuf shuf)
SLEEP = $(call which,SLEEP,gsleep sleep)
SORT = $(call which,SORT,gsort sort)
SPLIT = $(call which,SPLIT,gsplit split)
STAT = $(call which,STAT,gstat stat)
STDBUF = $(call which,STDBUF,gstdbuf stdbuf)
STTY = $(call which,STTY,gstty stty)
SUM = $(call which,SUM,gsum sum)
SYNC = $(call which,SYNC,gsync sync)
TAC = $(call which,TAC,gtac tac)
TAIL = $(call which,TAIL,gtail tail)
TEE = $(call which,TEE,gtee tee)
TEST = $(call which,TEST,gtest test)
TIMEOUT = $(call which,TIMEOUT,gtimeout timeout)
TOUCH = $(call which,TOUCH,gtouch touch)
TR = $(call which,TR,gtr tr)
TRUE = $(call which,TRUE,gtrue true)
TRUNCATE = $(call which,TRUNCATE,gtruncate truncate)
TSORT = $(call which,TSORT,gtsort tsort)
TTY = $(call which,TTY,gtty tty)
UNAME = $(call which,UNAME,guname uname)
UNEXPAND = $(call which,UNEXPAND,gunexpand unexpand)
UNIQ = $(call which,UNIQ,guniq uniq)
UNLINK = $(call which,UNLINK,gunlink unlink)
UPTIME = $(call which,UPTIME,guptime uptime)
USERS = $(call which,USERS,gusers users)
VDIR = $(call which,VDIR,gvdir vdir)
WC = $(call which,WC,gwc wc)
WHO = $(call which,WHO,gwho who)
WHOAMI = $(call which,WHOAMI,gwhoami whoami)
YES = $(call which,YES,gyes yes)

# coreutils: custom

CP = $(call which,CP,gcp cp) -Rp
LN = $(call which,LN,gln ln) -fn
MKDIR = $(call which,MKDIR,gmkdir mkdir) -p
MKTEMP = $(call which,MKTEMP,gmktemp mktemp) -t yplatform.XXXXXXXXXX
MV = $(call which,MV,gmv mv) -f
PARALLEL = $(call which,PARALLEL,gparallel parallel) --will-cite
RM = $(call which,RM,grm rm) -rf
XARGS = $(call which,XARGS,gxargs xargs) -r

# coreutils: make lazy. generated by
# echo "\$(foreach VAR,$(ls $(brew --prefix coreutils)/libexec/gnubin | grep -v -e '^\[$' -e '^logname$' -e '^pwd$' | tr '[:lower:]' '[:upper:]' | tr '\n' ' '),\$(call make-lazy,\$(VAR)))" # editorconfig-checker-disable-line
# ignoring [
# ignore logname - creates a LOGNAME var, sometimes exported, which should be =$USER (username), not a path
# ignore pwd - creates a PWD var, sometimes exported, which should be working dir not a path

$(foreach VAR,B2SUM BASE32 BASE64 BASENAME BASENC CAT CHCON CHGRP CHMOD CHOWN CHROOT CKSUM COMM CP CSPLIT CUT DATE DD DF DIR DIRCOLORS DIRNAME DU ECHO ENV EXPAND EXPR FACTOR FALSE FMT FOLD GROUPS HEAD HOSTID ID INSTALL JOIN KILL LINK LN LS MD5SUM MKDIR MKFIFO MKNOD MKTEMP MV NICE NL NOHUP NPROC NUMFMT OD PASTE PATHCHK PINKY PR PRINTENV PRINTF PTX READLINK REALPATH RM RMDIR RUNCON SEQ SHA1SUM SHA224SUM SHA256SUM SHA384SUM SHA512SUM SHRED SHUF SLEEP SORT SPLIT STAT STDBUF STTY SUM SYNC TAC TAIL TEE TEST TIMEOUT TOUCH TR TRUE TRUNCATE TSORT TTY UNAME UNEXPAND UNIQ UNLINK UPTIME USERS VDIR WC WHO WHOAMI YES ,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# ------------------------------------------------------------------------------

GNU_LOGNAME = $(call which,LOGNAME,glogname logname)
GNU_PWD = $(call which,LOGNAME,gpwd pwd)

$(foreach VAR,GNU_LOGNAME GNU_PWD,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# ------------------------------------------------------------------------------

# diffutils
CMP = $(call which,CMP,gcmp cmp)
DIFF = $(call which,DIFF,gdiff diff)
DIFF3 = $(call which,DIFF3,gdiff3 diff3)
SDIFF = $(call which,SDIFF,gsdiff sdiff)
$(foreach VAR,CMP DIFF DIFF3 SDIFF,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# findutils
FIND = $(call which,FIND,gfind find)
LOCATE = $(call which,LOCATE,glocate locate)
UPDATEDB = $(call which,UPDATEDB,gupdatedb updatedb)
XARGS = $(call which,XARGS,gxargs xargs)
$(foreach VAR,FIND LOCATE UPDATEDB XARGS,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# gawk
AWK = $(call which,AWK,gawk awk)
$(foreach VAR,AWK,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# gettext
ENVSUBST = $(call which,ENVSUBST,envsubst)
$(foreach VAR,ENVSUBST,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# grep
EGREP = $(call which,EGREP,gegrep egrep)
FGREP = $(call which,FGREP,gfgrep fgrep)
GREP = $(call which,GREP,ggrep grep)
$(foreach VAR,EGREP FGREP GREP,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# gnu-sed
SED = $(call which,SED,gsed sed)
$(foreach VAR,SED,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# gnu-tar
TAR = $(call which,TAR,gtar tar)
$(foreach VAR,TAR,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# patch
PATCH = $(call which,PATCH,gpatch patch)
$(foreach VAR,PATCH,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line

# watch
WATCH = $(call which,WATCH,gwatch watch)
$(foreach VAR,WATCH,$(call make-lazy,$(VAR))) # editorconfig-checker-disable-line
