#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

if [[ "${EUID}" != "0" ]]; then
    # Restart this shell script as root.
    ${SUDO} ${BASH_SOURCE[0]}
    exit 0
fi

function apt_update() {
    echo_do "aptitude: Updating..."
    apt-get update -y --fix-missing 2>&1 || {
        set -x
        # try to handle "Hash Sum mismatch" error
        apt-get clean
        rm -rf /var/lib/apt/lists/*
        # see https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1785778
        apt-get update -o Acquire::CompressionTypes::Order::=gz
        apt-get update -y --fix-missing
        set +x
    }
    echo_done
}

function apt_install() {
    local FORCE_YES="--allow-downgrades --allow-remove-essential --allow-change-held-packages"
    while read -u3 DPKG; do
        [[ -n "${DPKG}" ]] || continue

        echo_do "aptitude: Installing ${DPKG}..."
        # apt-get install -y --force-yes "${DPKG}"
        apt-get install -y ${FORCE_YES} "${DPKG}"
        echo_done
    done 3< <(echo "$@")
}

echo_do "Setup aptitude..."
apt_install software-properties-common
apt_update
apt-add-repository -y -u ppa:git-core/ppa
echo_done

echo_do "Setup debconf-utils..."
export DEBIAN_FRONTEND=noninteractive
apt_install debconf-utils
echo '* libraries/restart-without-asking boolean true' | debconf-set-selections
echo_done

echo_do "Setup locales..."
apt_install locales
locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales
echo_done

if [[ "${CI:-}" != "true" ]]; then
    echo_skip "Setup NTP to improve date-time sync..."
else
    echo_do "Setup NTP to improve date-time sync..."
    (
        # see https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1773687
        ln -sf /usr/share/zoneinfo/UTC /etc/localtime
        apt_install tzdata
        dpkg-reconfigure tzdata

        if which -a timedatectl; then
            timedatectl set-ntp no || true
        fi
        apt_install ntp
        # test that ntpd is working
        ntpq -p
    ) || true
    echo_done
fi

# Basic
echo_do "aptitude: Installing basic packages..."
DPKGS="$(cat <<-EOF
bash
bsdmainutils
build-essential
curl
file
git
python3-minimal
uuid-runtime
zlib1g-dev
EOF
)"
apt_install "${DPKGS}"
unset DPKGS
echo_done

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done
