#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

${SUPPORT_FIRECLOUD_DIR}/bootstrap/linux/bootstrap-sudo
[[ "${SF_SKIP_BREW_BOOTSTRAP:-}" = "true" ]] || \
    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap.inc.sh
[[ "${CI:-}" != "true" ]] || {
    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-install-ci.inc.sh
    hash -r
    source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh
}
source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap-brewfile.inc.sh

brew_config
brew_list
brew_printenv

# see https://github.com/Homebrew/brew/issues/5013
hash -r
