#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh
source ${SUPPORT_FIRECLOUD_DIR}/sh/package-managers/apt.inc.sh

if [[ "${EUID}" != "0" ]]; then
    # Restart this shell script as root.
    ${SF_SUDO} ${BASH_SOURCE[0]}
    exit 0
fi

export DEBIAN_FRONTEND=noninteractive

echo_do "Setup aptitude..."
apt_update

apt_install_one apt-transport-https
apt_install_one ca-certificates
apt_install_one software-properties-common
apt_install_one gnupg-agent

apt_install_one git
apt_install_one openssl
apt_install_one ssh-client
apt_install_one sudo
echo_done

echo_do "Setup debconf-utils..."
apt_install_one debconf-utils
echo '* libraries/restart-without-asking boolean true' | debconf-set-selections
echo_done

echo_do "Setup locales..."
apt_install_one locales
locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales
echo_done

if [[ "${CI:-}" != "true" ]]; then
    echo_skip "Setup NTP to improve date-time sync..."
else
    echo_do "Setup NTP to improve date-time sync..."
    (
        # see https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1773687
        ln -sf /usr/share/zoneinfo/UTC /etc/localtime
        apt_install_one tzdata
        dpkg-reconfigure tzdata

        if which -a timedatectl; then
            timedatectl set-ntp no || true
        fi
        apt_install_one ntp
        # test that ntpd is working
        ntpq -p
    ) || true
    echo_done
fi

# Basic
echo_do "aptitude: Installing basic packages..."
apt_install_one bsdmainutils
apt_install_one build-essential
apt_install_one uuid-runtime
apt_install_one zlib1g-dev

apt_install_one bash
apt_install_one curl
apt_install_one file
apt_install_one python3-minimal
echo_done

# scripts tend to call /usr/bin/pyhon to intend calling python2 or python3, whichever is available
[[ -e /usr/bin/python ]] || ln -s /usr/bin/python3 /usr/bin/python

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done
