#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh
source ${SUPPORT_FIRECLOUD_DIR}/sh/package-managers/yum.inc.sh

if [[ "${EUID}" != "0" ]]; then
    # Restart this shell script as root.
    ${SF_SUDO} ${BASH_SOURCE[0]}
    exit 0
fi

# keep in sync with dockerfiles/sf-centos/Dockerfile.build.sh
echo_do "Setup yum..."
yum_update

yum_install_one ca-certificates
yum_install_one gnupg

yum_install_one git
yum_install_one openssl
yum_install_one passwd
yum_install_one sudo
yum_install_one which
echo_done

# Basic
echo_do "yum: Installing basic packages..."
yum -y groupinstall "Development Tools"
# yum_install_one coreutils
yum_install_one coreutils-single
yum_install_one findutils
yum_install_one util-linux

yum_install_one python3

# scripts tend to call /usr/bin/pyhon to intend calling python2 or python3, whichever is available
[[ -e /usr/bin/python ]] || ln -s /usr/bin/python3 /usr/bin/python

echo_do "yum: Listing packages..."
yum list installed
echo_done
