#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

[[ "${YP_SKIP_SUDO_BOOTSTRAP:-}" = "true" ]] || \
    ${SUPPORT_FIRECLOUD_DIR}/bootstrap/linux/bootstrap-sudo-${OS_RELEASE_ID}

source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-util.inc.sh

echo_do "Print state info pre-homebrew..."
brew_system
brew_printenv
echo_done

[[ "${YP_SKIP_BREW_BOOTSTRAP:-}" = "true" ]] || \
    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap.inc.sh

[[ "${CI:-}" != "true" ]] || {
    echo_do "Print state info pre-bootstrap..."
    brew_system
    brew_printenv
    echo_done

    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-install-ci.inc.sh
    hash -r
    source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh
}

source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap-brewfile.inc.sh

echo_do "Print state info post-bootstrap..."
brew_system
brew_printenv
brew_config
brew_list
echo_done

# see https://github.com/Homebrew/brew/issues/5013
hash -r
