#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

if [[ "${SF_SKIP_COMMON_BOOTSTRAP:-}" = "true" ]]; then
    echo_info "SF_SKIP_COMMON_BOOTSTRAP=${SF_SKIP_COMMON_BOOTSTRAP}"
    echo_skip "ci/linux/bootstrap-sudo"
    echo_skip "source ci/brew-bootstrap.inc.sh"
    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-util.inc.sh
else
    ${SUPPORT_FIRECLOUD_DIR}/bootstrap/linux/bootstrap-sudo
    source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap.inc.sh
fi

source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap-brewfile.inc.sh

brew_config
brew_list
brew_printenv

# see https://github.com/Homebrew/brew/issues/5013
hash -r
