#!/usr/bin/env bash
set -euo pipefail

export SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

cd ${SUPPORT_FIRECLOUD_DIR}

SF_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "${SF_GIT_BRANCH}" = "master" ]]; then
    echo_warn "Pulling and resetting your local 'master' branch of support-firecloud"
    echo_warn "to the latest commit on 'origin/master'..."
    echo_info "Switch to another local branch to skip this behaviour."
    git reset
    git stash --all
    git checkout master
    git fetch
    git reset --hard origin/master
    git clean -xdf .
fi

# Bootstrap OS
OS=$(uname | tr "[A-Z]" "[a-z]")

# Check sudo permissions if using sudo.
echo_info "Bootstrapping with SUDO=${SUDO}..."
if [[ -z "${SUDO}" ]]; then
    true
elif [[ "${SUDO}" = "sf_nosudo" ]]; then
    prompt_q_to_continue "sudo is not available. Do you have root access instead?"
else
    echo "Enter your sudo password for bootstrap."
    ${SUDO} true || {
        echo_err "You need sudo/root access (called 'local admin rights' on MacOS) to bootstrap properly." \
            "If you don't have sudo/root access, try contacting the IT department."
        exit 1
    }
fi

# Execute the OS specific boostrap process.
${SUPPORT_FIRECLOUD_DIR}/ci/${OS}/bootstrap

# Offer to upgrade users login shell to homebrew's bash.
${SUPPORT_FIRECLOUD_DIR}/bin/use-homebrew-bash

# User feedback
echo
echo "Append 'source \"~/${SUPPORT_FIRECLOUD_DIR#${HOME}/}/sh/dev.inc.sh\"'"
echo "to your '~/.bashrc' or '~/.zshrc' or similar."
echo
echo "Restart your shell, and you're good to go."
