#!/usr/bin/env bash
set -euo pipefail

export SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Reset and upgrade SF
cd ${SUPPORT_FIRECLOUD_DIR}
git reset
git stash --all
git checkout master
git fetch
git reset --hard origin/master
git clean -xdf .

# Bootstrap OS
OS=$(uname | tr "[A-Z]" "[a-z]")

sudo true || {
    >&2 echo "[ERROR] You need local admin rights to properly bootstrap." \
    "If you don't have local admin rights, try contacting the IT department."
    exit 1
}

# Execute the OS specific boostrap process.
${SUPPORT_FIRECLOUD_DIR}/ci/${OS}/bootstrap

# Offer to upgrade users login shell to homebrew's bash.
${SUPPORT_FIRECLOUD_DIR}/bin/use-homebrew-bash

# User feedback
echo
echo "Append 'source \"~/${SUPPORT_FIRECLOUD_DIR#${HOME}/}/sh/dev.inc.sh\"'"
echo "to your '~/.bashrc' or '~/.zshrc' or similar."
echo
echo "Restart your shell, and you're good to go."
