#!/usr/bin/env bash
set -euo pipefail

[[ $(uname) != "Darwin" ]] || {
    xcode-select --install 2>&1 | grep -q -Fx 'xcode-select: error: command line tools are already installed, use "Software Update" to install updates' || { # editorconfig-checker-disable-line
        echo xcode-select --install
        prompt_q_to_continue "Press ENTER when Command Line Tools finishes to be installed."
    }
}

export YP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source ${YP_DIR}/sh/common.inc.sh

cd ${YP_DIR}

! command -v git >/dev/null || {
    YP_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if [[ "${YP_GIT_BRANCH}" = "master" ]]; then
        echo_warn "Pulling and resetting your local 'master' branch of yplatform"
        echo_warn "to the latest commit on 'origin/master'..."
        echo_info "Switch to another local branch to skip this behaviour."
        git reset
        git stash --all
        git checkout master
        git fetch
        git reset --hard origin/master
        git clean -xdf .
    fi
}

# Check sudo permissions if using sudo.
echo_info "Bootstrapping with YP_SUDO=${YP_SUDO}..."
if [[ -z "${YP_SUDO}" ]]; then
    true
elif [[ "${YP_SUDO}" = "yp_nosudo_fallback" ]]; then
    prompt_q_to_continue "sudo is not available. Do you have root access instead?"
else
    echo "Enter your sudo password for bootstrap."
    ${YP_SUDO} true || {
        echo_err "You need sudo/root access (called 'local admin rights' on MacOS) to bootstrap properly."
        echo_err "If you don't have sudo/root access, try contacting the IT department."
        exit 1
    }
fi

# Execute the OS specific boostrap process.
${YP_DIR}/bootstrap/${OS_SHORT}/bootstrap

# Offer to upgrade users login shell to homebrew's bash.
${YP_DIR}/bin/use-homebrew-bash

# User feedback
echo
echo "Append 'source ~/${YP_DIR#"${HOME}"/}/sh/dev.inc.sh'"
echo "to your '~/.bashrc' or '~/.zshrc' or similar."
echo
echo "Restart your shell, and you're good to go."
