#!/usr/bin/env bash
set -euo pipefail
set -x

[ "${EUID}" -eq 0 ] || {
    sudo "${BASH_SOURCE[0]}"
    exit 0
}

function on_exit() {
    local STATUS=$?
    set +x
    exit ${STATUS}
}

trap on_exit EXIT

echo "Upgrading aptitude..."
apt-get install -y --force-yes software-properties-common
apt-add-repository -y ppa:git-core/ppa
apt-get update
if [ "${TRAVIS:-}" = "true" ]; then
    apt-mark hold postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6
fi
apt-get upgrade -y

echo "Installing/Upgrading git..."
apt-get install -y --force-yes git

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

function apt_install() {
    echo "${DPKGS}" | while read DPKG; do
        apt-get install -y --force-yes ${DPKG}
    done
}

# Basic
echo_do "Installing basic packages..."
DPKGS="$(cat <<-'EOF'
autoconf
automake
bsdmainutils
build-essential
realpath
software-properties-common
tar
uuid-runtime
zip
EOF
)"
apt_install
echo_done

# Misc
echo_do "Installing miscellaneous packages..."
DPKGS="$(cat <<-'EOF'
bash
curl
git
jq
python
python3
python-pip
python3-pip
wget
EOF
)"
apt_install
echo_done

echo_do "Installing JQ..."
${SUPPORT_FIRECLOUD_DIR}/ci/linux/install-jq
echo_done

echo_do "Installing GNU Make..."
${SUPPORT_FIRECLOUD_DIR}/ci/linux/install-make
echo_done

# AWS
echo_do "Installing AWS utils..."
pip install --upgrade awscli
pip install --upgrade awslogs
aws configure set s3.signature_version s3v4
echo_done

echo_do "Printenv..."
printenv
echo_done

echo_do "Listing packages..."
apt list --installed
echo_done
