#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

${SUPPORT_FIRECLOUD_DIR}/ci/linux/bootstrap-sudo

brew_bootstrap_linux() {
    local BREWFILE_INC_SH=${GIT_ROOT}/Brewfile.inc.sh
    [[ ! -f "${BREWFILE_INC_SH}" ]] || {
        echo_info "brew: Detected predefined packages in ${BREWFILE_INC_SH}"
        source ${BREWFILE_INC_SH}
        return 0
    }

    source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-common.inc.sh
}

source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-bootstrap.inc.sh
brew_bootstrap_linux
brew_list

echo_do "Printenv..."
printenv
echo_done
