#!/usr/bin/env bash
set -euo pipefail

[ ${EUID} -eq 0 ] || {
    sudo ${BASH_SOURCE[0]}
    exit 0
}

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

apt_install() {
    echo "$@" | while read DPKG; do
        echo_do "aptitude: Installing ${DPKG}..."
        apt-get install -y --force-yes "${DPKG}"
        echo_done
    done
}

echo_do "aptitude: Updating..."
apt_install "software-properties-common"
apt-add-repository -y ppa:git-core/ppa
apt-get update
echo_done

# Basic
echo_do "aptitude: Installing basic packages..."
DPKGS="$(cat <<-EOF
bash
bsdmainutils
build-essential
curl
file
git
uuid-runtime
EOF
)"
apt_install "${DPKGS}"
echo_done

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done
