#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

${SUPPORT_FIRECLOUD_DIR}/ci/linux/bootstrap-sudo

brew_bootstrap_linux() {
    [[ -z "${BREW_FORMULAE:-}" ]] || {
        echo_info "brew: Detected predefined packages ${BREW_FORMULAE}"
        return 0
    }

    source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-common.inc.sh
}

source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-bootstrap.inc.sh
brew_bootstrap_linux
brew_list

source ${SUPPORT_FIRECLOUD_DIR}/ci/maybe-npm.inc.sh

echo_do "Printenv..."
printenv
echo_done
