#!/usr/bin/env bash
set -euo pipefail

[ ${EUID} -eq 0 ] || {
    sudo ${BASH_SOURCE[0]}
    exit 0
}

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

apt_install() {
    while read -u3 DPKG; do
        echo_do "aptitude: Installing ${DPKG}..."
        apt-get install -y --force-yes "${DPKG}"
        echo_done
    done 3< <(echo "$@")
}

echo_do "aptitude: Updating..."
apt_install "software-properties-common"
apt-add-repository -y ppa:git-core/ppa
apt-get update
echo_done

apt_install locales
locale-gen en_US en_US.UTF-8
dpkg-reconfigure --frontend=noninteractive locales

# improve date-time (ntp) sync
(
    timedatectl set-ntp no
    apt_install ntp
) || true

# Basic
echo_do "aptitude: Installing basic packages..."
DPKGS="$(cat <<-EOF
bash
bsdmainutils
build-essential
curl
file
git
rsync
uuid-runtime
EOF
)"
apt_install "${DPKGS}"
echo_done

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done
