# docker build . --file ci/linux/Dockerfile.ubuntu.xenial --tag sf-ubuntu-xenial
FROM ubuntu:16.04

ADD . /support-firecloud
RUN IMAGE_TAG=${IMAGE_TAG} \
    SF_CI_BREW_INSTALL=${SF_CI_BREW_INSTALL} \
    /support-firecloud/ci/linux/Dockerfile.ubuntu.xenial.sh
