# docker build . --file ci/linux/Dockerfile.ubuntu.xenial --tag sf-ubuntu-bionic
FROM ubuntu:18.04

ARG IMAGE_TAG
ARG SF_CI_BREW_INSTALL

ADD . /support-firecloud
RUN IMAGE_TAG=${IMAGE_TAG} \
    SF_CI_BREW_INSTALL=${SF_CI_BREW_INSTALL} \
    /support-firecloud/ci/linux/Dockerfile.ubuntu.bionic.sh
