#!/usr/bin/env bash
SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

PKG=
VSN=
TAR_NAME=
TAR_URL=
CACHE_DIR=${SUPPORT_FIRECLOUD_CACHE_DIR}
CACHE_KEEP=true
PREFIX=/usr/local

[ "${EUID}" -eq 0 ] || PREFIX=${HOME}/.local

while [ $# -gt 0 ]; do
    case "$1" in
        --pkg)
            PKG=$2
            shift 2
            ;;
        --vsn)
            VSN=$2
            shift 2
            ;;
        --tar-name)
            TAR_NAME=$2
            shift 2
            ;;
        --tar-url)
            TAR_URL=$2
            shift 2
            ;;
        --prefix)
            PREFIX=$2
            shift 2
            ;;
        --dir)
            CACHE_DIR=$2
            shift 2
            ;;
        --no-keep)
            CACHE_KEEP=false
            shift
            ;;
        -h|--help)
            sh_script_usage
            ;;
        -v|--version)
            sh_script_version
            ;;
        -*)
            sh_script_usage
            ;;
        *)
            sh_script_usage
            ;;
    esac
done

[ -n "${VSN}" ] || {
    echo_err "Please provide a --version."
    exit 1
}

[ -n "${TAR_NAME}" ] || TAR_NAME=${PKG}-${VSN}
[ -n "${TAR_URL}" ] || TAR_URL=https://ftp.gnu.org/gnu/${PKG}/${TAR_NAME}.tar.gz

TAR_NAME="$(echo "${TAR_NAME}" | PKG=${PKG} VSN=${VSN} envsubst)"
TAR_URL="$(echo "${TAR_URL}" | PKG=${PKG} VSN=${VSN} TAR_NAME=${TAR_NAME} envsubst)"

CONFIGURE_ARGS="${CONFIGURE_ARGS:-} --prefix=${PREFIX}"

cd ${CACHE_DIR}

[ -d ${TAR_NAME} ] || (
    curl -LO "${TAR_URL}"
    tar xf ${TAR_NAME}.tar.gz
    cd ${TAR_NAME}
    ./configure ${CONFIGURE_ARGS}
    make
)

(
    cd ${TAR_NAME}
    make install
)

[ ${CACHE_KEEP} = true ] || {
    rm -rf ${TAR_NAME}*
}
