#!/usr/bin/env bash
SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

VSN=${VSN_BASH:=4.4}
CACHE_DIR=${SUPPORT_FIRECLOUD_CACHE_DIR}
CACHE_KEEP=true
PREFIX=/usr/local

[ "${EUID}" -eq 0 ] || PREFIX=${HOME}/.local

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)
            PREFIX=$2
            shift 2
            ;;
        --dir)
            CACHE_DIR=$2
            shift 2
            ;;
        --keep)
            CACHE_KEEP=true
            shift
            ;;
        --vsn)
            VSN=$2
            shift 2
            ;;
        -h|--help)
            sh_script_usage
            ;;
        -v|--version)
            sh_script_version
            ;;
        -*)
            sh_script_usage
            ;;
        *)
            sh_script_usage
            ;;
    esac
done

[ -n "${VSN}" ] || {
    echo_err "Please provide a --version."
    exit 1
}

TAR_NAME=bash-${VSN}
TAR_URL=https://ftp.gnu.org/gnu/bash/${TAR_NAME}.tar.gz
CONFIGURE_ARGS="${CONFIGURE_ARGS:-} --prefix=${PREFIX}"

cd ${CACHE_DIR}

[ -d ${TAR_NAME} ] || (
    curl -LO "${TAR_URL}"
    tar xf ${TAR_NAME}.tar.gz
    cd ${TAR_NAME}
    ./configure ${CONFIGURE_ARGS}
    make
)

(
    cd ${TAR_NAME}
    make install
)

[ ${CACHE_KEEP} ] || {
    rm -rf ${TAR_NAME}*
}
