#!/usr/bin/env bash
# shellcheck disable=SC2034
true

function sf_ci_env_semaphore() {
    [[ "${SEMAPHORE:-}" = "true" ]] || return 0

    export CI=true
    CI_NAME=Semaphore
    CI_PLATFORM=semaphore
    CI_SERVER_HOST=${SEMAPHORE_ORGANIZATION_URL:-semaphoreci.com}
    CI_SERVER_HOST=${CI_SERVER_HOST#*://}
    CI_REPO_SLUG=${SEMAPHORE_GIT_REPO_SLUG:-}
    CI_ROOT=${SEMAPHORE_GIT_DIR:-}

    CI_IS_CRON=${SEMAPHORE_WORKFLOW_TRIGGERED_BY_SCHEDULE:-}
    CI_IS_PR=
    [[ -z "${SEMAPHORE_GIT_PR_SLUG:-}" ]] || CI_IS_PR=true

    CI_JOB_ID=${SEMAPHORE_JOB_ID:-}
    CI_PIPELINE_ID=${SEMAPHORE_WORKFLOW_ID:-}
    CI_JOB_URL="${SEMAPHORE_ORGANIZATION_URL:-}/jobs/${CI_JOB_ID}"
    CI_PIPELINE_URL="${SEMAPHORE_ORGANIZATION_URL:-}/workflows/${CI_PIPELINE_ID}"

    CI_PR_URL=
    CI_PR_REPO_SLUG=
    CI_PR_GIT_HASH=
    CI_PR_GIT_BRANCH=
    [[ "${CI_IS_PR}" != "true" ]] || {
        CI_PR_URL=https://github.com/${CI_REPO_SLUG}/pull/${SEMAPHORE_GIT_PR_NUMBER:-}
        CI_PR_REPO_SLUG=${SEMAPHORE_GIT_PR_SLUG:-}
        CI_PR_GIT_HASH=${SEMAPHORE_GIT_PR_SHA:-}
        CI_PR_GIT_BRANCH=${SEMAPHORE_GIT_PR_BRANCH:-}
    }

    CI_GIT_HASH=${SEMAPHORE_GIT_SHA:-}
    CI_GIT_BRANCH=${SEMAPHORE_GIT_BRANCH:-}
    CI_GIT_TAG=${SEMAPHORE_GIT_TAG_NAME:-}

    CI_DEBUG_MODE=${CI_DEBUG_MODE:-}
}

function sf_ci_printvars_semaphore() {
    printenv | grep \
        -e "^CI[=_]" \
        -e "^SEMAPHORE[=_]"
}

function sf_ci_known_env_semaphore() {
    # see https://docs.semaphoreci.com/ci-cd-environment/environment-variables/
    cat <<EOF
CI
SEMAPHORE
SEMAPHORE_PROJECT_NAME
SEMAPHORE_PROJECT_ID
SEMAPHORE_ORGANIZATION_URL
SEMAPHORE_JOB_NAME
SEMAPHORE_JOB_ID
SEMAPHORE_JOB_RESULT
SEMAPHORE_WORKFLOW_ID
SEMAPHORE_WORKFLOW_NUMBER
SEMAPHORE_WORKFLOW_RERUN
SEMAPHORE_WORKFLOW_TRIGGERED_BY_HOOK
SEMAPHORE_WORKFLOW_TRIGGERED_BY_SCHEDULE
SEMAPHORE_WORKFLOW_TRIGGERED_BY_API
SEMAPHORE_PIPELINE_ID
SEMAPHORE_PIPELINE_PROMOTION
SEMAPHORE_PIPELINE_PROMOTED_BY
SEMAPHORE_PIPELINE_RERUN
SEMAPHORE_AGENT_MACHINE_TYPE
SEMAPHORE_AGENT_MACHINE_OS_IMAGE
SEMAPHORE_AGENT_MACHINE_ENVIRONMENT_TYPE
SEMAPHORE_GIT_SHA
SEMAPHORE_GIT_URL
SEMAPHORE_GIT_BRANCH
SEMAPHORE_GIT_DIR
SEMAPHORE_GIT_REPO_SLUG
SEMAPHORE_GIT_REF_TYPE
SEMAPHORE_GIT_REF
SEMAPHORE_GIT_COMMIT_RANGE
SEMAPHORE_GIT_TAG_NAME
SEMAPHORE_GIT_PR_BRANCH
SEMAPHORE_GIT_PR_SLUG
SEMAPHORE_GIT_PR_SHA
SEMAPHORE_GIT_PR_NUMBER
SEMAPHORE_GIT_PR_NAME
SEMAPHORE_CACHE_USERNAME
SEMAPHORE_CACHE_URL
SEMAPHORE_CACHE_PRIVATE_KEY_PATH
SEMAPHORE_REGISTRY_USERNAME
SEMAPHORE_REGISTRY_PASSWORD
SEMAPHORE_REGISTRY_URL
EOF
    # undocumented but observed
    cat <<EOF
SEMAPHORE_ARTIFACT_TOKEN
SEMAPHORE_ERLANG_VERSION
SEMAPHORE_PIPELINE_0_ARTEFACT_ID
SEMAPHORE_PIPELINE_ARTEFACT_ID
SEMAPHORE_SCALA_VERSION
SEMAPHORE_WORKFLOW_HOOK_SOURCE
EOF
}
