#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/bin/common.inc.sh

echo_do "aptitude: Listing packages..."
apt list --installed
echo_done

brew_bootstrap_linux_nosudo() {
    [[ -z "${BREW_FORMULAE:-}" ]] || {
        echo_info "brew: Detected predefined packages ${BREW_FORMULAE}"
        return 0
    }

    source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-minimal.inc.sh

    if [[ "${TRAVIS:-}" = "true" ]]; then
        echo_do "brew: Installing AWS utils (optimized for Travis)..."
        pip2 install --user --upgrade --ignore-installed awscli
        pip2 install --user --upgrade --ignore-installed awslogs
        aws configure set s3.signature_version s3v4
        echo_done
    else
        source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-install-minimal.inc.sh
    fi
}

source ${SUPPORT_FIRECLOUD_DIR}/ci/brew-bootstrap.inc.sh
brew_bootstrap_linux_nosudo
brew_list

source ${SUPPORT_FIRECLOUD_DIR}/ci/maybe-npm.inc.sh

echo_do "Printenv..."
printenv
echo_done
