#!/usr/bin/env bash
set -euo pipefail

export HOMEBREW_DISPLAY_INSTALL_TIMES=1
export HOMEBREW_FAIL_LOG_LINES=100
export HOMEBREW_GITHUB_API_TOKEN=${HOMEBREW_GITHUB_API_TOKEN:-${YP_GH_TOKEN:-}}
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1
# export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_INSTALL_FROM_API=1
export HOMEBREW_VERBOSE_USING_DOTS=1
