#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

RELEASE_ID=
RELEASE_VERSION_ID=

DOCKER_ORG=rokmoln
DOCKER_IMAGE_FROM=
DOCKER_IMAGE_NAME=
DOCKER_IMAGE_TAG=$(cat ${SUPPORT_FIRECLOUD_DIR}/package.json | jq -r ".version")-local
DOCKERFILE=

SF_CI_BREW_INSTALL=minimal

while [[ $# -gt 0 ]]; do
    case "$1" in
        --docker-image-from)
            DOCKER_IMAGE_FROM=$2
            shift 2
            ;;
        --docker-image-name)
            DOCKER_IMAGE_NAME=$2
            shift 2
            ;;
        --docker-image-tag)
            DOCKER_IMAGE_TAG=$2
            shift 2
            ;;
        --sf-ci-brew-install)
            SF_CI_BREW_INSTALL=$2
            shift 2
            ;;
        -h|--help)
            sh_script_usage
            ;;
        -v|--version)
            sh_script_version
            ;;
        -* )
            sh_script_usage
            ;;
        *)
            break
            ;;
    esac
done

MYSELF=${BASH_SOURCE[0]}
OS_RELEASE=$(dirname ${MYSELF})/os-release

RELEASE_ID="$(source ${OS_RELEASE} && echo ${ID})"
RELEASE_VERSION_ID="$(source ${OS_RELEASE} && echo ${VERSION_ID})"

[[ -n "${DOCKER_IMAGE_FROM}" ]] || {
    DOCKER_IMAGE_FROM=${RELEASE_ID}:${RELEASE_VERSION_ID}
}

[[ -n "${DOCKERFILE}" ]] || \
    DOCKERFILE=${SUPPORT_FIRECLOUD_DIR}/dockerfiles/sf-${RELEASE_ID}-${RELEASE_VERSION_ID}/Dockerfile
[[ -n "${DOCKER_IMAGE_NAME}" ]] || \
    DOCKER_IMAGE_NAME=sf-${RELEASE_ID}-${RELEASE_VERSION_ID}-${SF_CI_BREW_INSTALL}

echo_do "Building ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}..."
exe docker build ${SUPPORT_FIRECLOUD_DIR} \
    --file ${DOCKERFILE} \
    --tag ${DOCKER_ORG}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} \
    --build-arg SF_DOCKER_CI_FROM=${DOCKER_IMAGE_FROM} \
    --build-arg SF_DOCKER_CI_IMAGE_NAME=${DOCKER_IMAGE_NAME} \
    --build-arg SF_DOCKER_CI_IMAGE_TAG=${DOCKER_IMAGE_TAG} \
    --build-arg SF_CI_BREW_INSTALL=${SF_CI_BREW_INSTALL}
echo_done
