#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/ci/darwin/bootstrap

BREW_FORMULAE="$(cat <<-EOF
erlang
graphviz
nodejs
EOF
)"
brew_install "${BREW_FORMULAE}"

# NPM
npm install --global npm
npm install --global json

# Upgrade default shell, if bash
echo "/usr/local/bin/bash" | tee -a /etc/shells
[ "${SHELL:-}" != "/bin/bash" ] || chsh -s /usr/local/bin/bash

# Install Xcode/Command Line Tools
xcode-select --install
