#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/ci/darwin/bootstrap

BREW_FORMULAE="$(cat <<-EOF
erlang
graphviz
nodejs
EOF
)"
brew_install "${BREW_FORMULAE}"

# NPM
npm install --global npm
npm install --global json

# Install Xcode/Command Line Tools
xcode-select --install

# Upgrade default shell, if bash
[ "${SHELL:-}" != "/bin/bash" ] || {
    echo "Your default shell is ${SHELL}, which is system's default bash."
    echo "You should upgrade to use homebrew's newer bash."
    read -p "You can skip upgrading by pressing 's'. Anything else will do the upgrade." -n 1 -r
    [ "${REPLY}" = "s" ] || {
        sudo tee -a /etc/shells <<EOF
/usr/local/bin/bash
EOF
        chsh -s /usr/local/bin/bash
        echo "Please open up a new terminal window to switch to the new bash."
    }
}
