#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/ci/darwin/bootstrap

# Upgrade default shell, if bash
[ "${SHELL:-}" != "/bin/bash" ] || {
    echo "Your default shell is ${SHELL}, which is system's default bash."
    echo "You should upgrade to use homebrew's newer bash."
    read -p "You can skip upgrading by pressing 's'. Anything else will do the upgrade." -n 1 -r
    [ "${REPLY}" = "s" ] || {
        sudo tee -a /etc/shells <<EOF
/usr/local/bin/bash
EOF
        chsh -s /usr/local/bin/bash
        echo "Restart your shell, and you're good to go."
    }
}
