#!/usr/bin/env bash
set -euo pipefail

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

[[ "${SF_DEV_INC_SH:-}" = true ]] || {
    >&2 echo "[ERROR] You need to run this on a bootstrap dev machine where SF_DEV_INC_SH=true."
    exit 1
}

source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-util.inc.sh
# shellcheck disable=SC2034
SF_SKIP_COMMON_BOOTSTRAP=true
source ${SUPPORT_FIRECLOUD_DIR}/bootstrap/brew-bootstrap-brewfile.inc.sh
