#!/usr/bin/env bash
set -euo pipefail
set -x

function on_exit() {
    local STATUS=$?
    set +x
    exit ${STATUS}
}

trap on_exit EXIT

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

${SUPPORT_FIRECLOUD_DIR}/ci/darwin/bootstrap

brew install \
    erlang \
    graphviz \
    nodejs

# JSON
npm install --global json
