#!/usr/bin/env bash
set -euo pipefail
set -x

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${DIR}/CONST-VSN.inc

[ "${EUID}" -eq 0 ] || [ -n "${TEAMCITY_VERSION}" ] || {
  echo >&2 "You need to run this target with sudo or on TeamCity under tracks"
  exit 1
}

${DIR}/deps-os-linux
