#!/usr/bin/env bash
set -euo pipefail
set -x

[ "${EUID}" -eq 0 ] || [ -n "${TEAMCITY_VERSION}" ] || {
    >&2 echo "Run as root"
    exit 1
}

function on_exit() {
    local STATUS=$?
    set +x
    exit ${STATUS}
}

trap on_exit EXIT

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
${SUPPORT_FIRECLOUD_DIR}/ci/linux/bootstrap

apt-get install -y --force-yes \
    gettext \
    graphviz \
    libonig-dev \
    texinfo

# Erlang
curl -O https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
dpkg -i erlang-solutions_1.0_all.deb

# NodeJS (latest)
# see https://github.com/nodesource/distributions/issues/318
LATEST_VSN_NODE=9
while true; do
    curl -f -sL https://deb.nodesource.com/setup_$((LATEST_VSN_NODE+1)).x >/dev/null || break
    LATEST_VSN_NODE=$((LATEST_VSN_NODE+1))
done
curl -sL https://deb.nodesource.com/setup_${LATEST_VSN_NODE}.x | bash -
# apt-get update # happens in the nodesource.com script

apt-get install -y --force-yes \
    erlang \
    nodejs

# NPM
npm install --global npm
npm install --global json
