#!/usr/bin/env bash
set -euo pipefail

YP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source ${YP_DIR}/sh/common.inc.sh

DOCKER_OS_RELEASE_ID=
DOCKER_OS_RELEASE_VERSION_ID=

DOCKER_ORG=ysoftwareab
DOCKER_IMAGE_FROM=
DOCKER_IMAGE_NAME=
DOCKER_IMAGE_TAG=$(cat ${YP_DIR}/package.json | jq -r ".version")-local
DOCKERFILE=

YP_CI_BREW_INSTALL=minimal

while [[ $# -gt 0 ]]; do
    case "$1" in
        --docker-image-from)
            DOCKER_IMAGE_FROM=$2
            shift 2
            ;;
        --docker-image-name)
            DOCKER_IMAGE_NAME=$2
            shift 2
            ;;
        --docker-image-tag)
            DOCKER_IMAGE_TAG=$2
            shift 2
            ;;
        --yp-ci-brew-install)
            YP_CI_BREW_INSTALL=$2
            shift 2
            ;;
        -h|--help)
            sh_script_usage
            ;;
        -v|--version)
            sh_script_version
            ;;
        -* )
            sh_script_usage
            ;;
        *)
            break
            ;;
    esac
done

MYSELF=${BASH_SOURCE[0]}
OS_RELEASE_DIR="$(cd "$(dirname ${MYSELF})" && pwd)"
OS_RELEASE_FILE=$(dirname ${MYSELF})/os-release

DOCKER_OS_RELEASE_ID="$(source ${OS_RELEASE_FILE} && echo ${ID})"
DOCKER_OS_RELEASE_VERSION_ID="$(source ${OS_RELEASE_FILE} && echo ${VERSION_ID:-0})"

OS_RELEASE_DIR2="${YP_DIR}/dockerfiles/yp-${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID}"
[[ "${OS_RELEASE_DIR}" = "${OS_RELEASE_DIR2}" ]] || {
    echo_info "OS_RELEASE_DIR=${OS_RELEASE_DIR}"
    echo_info "OS_RELEASE_DIR2=${OS_RELEASE_DIR2}"
    echo_err "Inferred directory doesn't match this script's directory."
    exit 1
}

[[ -n "${DOCKER_IMAGE_FROM}" ]] || {
    case ${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID} in
        arch-0)
            DOCKER_IMAGE_FROM=archlinux:latest
            ;;
        *)
            DOCKER_IMAGE_FROM=${DOCKER_OS_RELEASE_ID}:${DOCKER_OS_RELEASE_VERSION_ID}
            ;;
    esac
}

[[ -n "${DOCKERFILE}" ]] || \
    DOCKERFILE=$(readlink -f ${OS_RELEASE_DIR}/Dockerfile)

[[ -n "${DOCKER_IMAGE_NAME}" ]] || \
    DOCKER_IMAGE_NAME=yp-${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID}-${YP_CI_BREW_INSTALL}

echo_do "Building ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}..."
exe docker build ${YP_DIR} \
    --file ${DOCKERFILE} \
    --tag ${DOCKER_ORG}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} \
    --build-arg YP_CI_BREW_INSTALL=${YP_CI_BREW_INSTALL} \
    --build-arg YP_DOCKER_CI_FROM=${DOCKER_IMAGE_FROM} \
    --build-arg YP_DOCKER_CI_IMAGE_NAME=${DOCKER_IMAGE_NAME} \
    --build-arg YP_DOCKER_CI_IMAGE_TAG=${DOCKER_IMAGE_TAG} \
    --build-arg YP_OS_RELEASE_DIR=${OS_RELEASE_DIR#"${YP_DIR}"/}
echo_done
