#!/usr/bin/env bash
set -euo pipefail

YP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null && pwd)"
source ${YP_DIR}/sh/common.inc.sh

MYSELF=${BASH_SOURCE[0]}
OS_RELEASE_DIR="$(cd "$(dirname ${MYSELF})" >/dev/null && pwd)"
OS_RELEASE_FILE=${OS_RELEASE_DIR}/os-release

DOCKER_OS_RELEASE_ID="$(source ${OS_RELEASE_FILE} && echo ${ID})"
DOCKER_OS_RELEASE_VERSION_ID="$(source ${OS_RELEASE_FILE} && echo ${VERSION_ID:-0})"
case ${DOCKER_OS_RELEASE_ID} in
    alpine)
        # track minor for alpine, not patch
        # shellcheck disable=SC2206
        DOCKER_OS_RELEASE_VERSION_ID_ARR=( ${DOCKER_OS_RELEASE_VERSION_ID//./ } )
        DOCKER_OS_RELEASE_VERSION_ID=${DOCKER_OS_RELEASE_VERSION_ID_ARR[0]}.${DOCKER_OS_RELEASE_VERSION_ID_ARR[1]}
        ;;
    *)
        ;;
esac

VANILLA=
COMMAND=
case ${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID} in
  alpine-*)
    VANILLA=ruby:2.6-alpine${DOCKER_OS_RELEASE_VERSION_ID}
    # shellcheck disable=SC2209
    COMMAND=sh
    ;;
  amzn-*)
    VANILLA=amazonlinux:latest
    ;;
  arch-0)
    VANILLA=archlinux:latest
    ;;
  centos-*)
    VANILLA=quay.io/centos/centos:stream${DOCKER_OS_RELEASE_VERSION_ID}
    ;;
  rhel-*)
    VANILLA=redhat/ubi8:${DOCKER_OS_RELEASE_VERSION_ID}
    ;;
  *)
    VANILLA=${DOCKER_OS_RELEASE_ID}:${DOCKER_OS_RELEASE_VERSION_ID}
    ;;
esac

# vanilla
# yp-minimal or yp-minimal:<tag>
# yp-common or yp-common:<tag>

FLAVOUR=$1
shift

case "${FLAVOUR}" in
    vanilla)
        NAME="${VANILLA}"
        ;;
    yp-minimal|yp-minimal:*|yp-common|yp-common:*)
        YP_CI_BREW_INSTALL=${FLAVOUR:3}
        TAG=${YP_CI_BREW_INSTALL##*:}
        YP_CI_BREW_INSTALL=${YP_CI_BREW_INSTALL%%:*}
        [[ "${YP_CI_BREW_INSTALL}" != "${TAG}" ]] || TAG=$(cat ${YP_DIR}/package.json | jq -r ".version")
        NAME="ysoftwareab/yp-${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID}-${YP_CI_BREW_INSTALL}:${TAG}"
        ;;
    *)
        echo_err "Unknown FLAVOUR=${FLAVOUR}."
        exit 1
        ;;
esac

exe docker run \
    --platform linux/amd64 \
    --rm \
    -it \
    "$@" \
    ${NAME} \
    ${COMMAND}
