#!/usr/bin/env bash
set -euo pipefail

YP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null && pwd)"
source ${YP_DIR}/sh/common.inc.sh

MYSELF=${BASH_SOURCE[0]}
OS_RELEASE_DIR="$(cd "$(dirname ${MYSELF})" >/dev/null && pwd)"

source ${YP_DIR}/dockerfiles/util/os-release.inc.sh

# vanilla
# yp-minimal or yp-minimal:<tag>
# yp-common or yp-common:<tag>

FLAVOUR=$1
shift

case "${FLAVOUR}" in
  vanilla)
    exe docker scan --accept-license --dependency-tree --severity=medium \
      ${OS_RELEASE_BASE}
    exit 0
    ;;
  yp-minimal|yp-minimal:*|yp-common|yp-common:*)
    YP_CI_BREW_INSTALL=${FLAVOUR:3}
    TAG=${YP_CI_BREW_INSTALL##*:}
    YP_CI_BREW_INSTALL=${YP_CI_BREW_INSTALL%%:*}
    [[ "${YP_CI_BREW_INSTALL}" != "${TAG}" ]] || TAG=$(cat ${YP_DIR}/package.json | jq -r ".version")
    NAME="ysoftwareab/yp-${DOCKER_OS_RELEASE_ID}-${DOCKER_OS_RELEASE_VERSION_ID}-${YP_CI_BREW_INSTALL}:${TAG}"
    ;;
  *)
    echo_err "Unknown FLAVOUR=${FLAVOUR}."
    exit 1
    ;;
esac

exe docker scan --accept-license --dependency-tree --severity=medium \
  --file ${OS_RELEASE_DIR}/Dockerfile --exclude-base ${NAME}
