name: debug
'on':
  workflow_dispatch: null
jobs:
  gitref:
    timeout-minutes: 30
    name: gitref
    runs-on: ubuntu-20.04
    steps:
      - name: step1
        uses: ysoftwareab/yplatform/.github/actions/github-composite-env@debug-github-action-compose-env
        with:
          step: 1
      - name: step2
        uses: ysoftwareab/yplatform/.github/actions/github-composite-env@debug-github-action-compose-env
        with:
          step: 2
      - name: check
        if: always()
        shell: bash
        run: |
          set -x
          STEP=1
          VAR="STEP_${STEP}_COMPOSITE_1"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_2"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_3"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_4"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_5"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_6"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE"
          test "${!VAR}" = "6"
          VAR="STEP_COMPOSITE"
          test "${!VAR}" = "${STEP}6"

  local:
    timeout-minutes: 30
    name: local
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: step1
        uses: ./.github/actions/github-composite-env
        with:
          step: 1
      - name: step2
        uses: ./.github/actions/github-composite-env
        with:
          step: 2
      - name: check
        if: always()
        shell: bash
        run: |
          set -x
          STEP=2
          VAR="STEP_${STEP}_COMPOSITE_1"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_2"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_3"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_4"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_5"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE_6"
          test "${!VAR}" = "true"
          VAR="STEP_${STEP}_COMPOSITE"
          test "${!VAR}" = "6"
          VAR="STEP_COMPOSITE"
          test "${!VAR}" = "${STEP}6"
