name: debug
'on':
  workflow_dispatch: null
jobs:
  gitref:
    timeout-minutes: 30
    name: gitref
    runs-on: ubuntu-20.04
    steps:
      - name: step1
        uses: ysoftwareab/yplatform/.github/actions/github-composite-env@debug-github-action-compose-env
        with:
          step: 1
      - name: step2
        uses: ysoftwareab/yplatform/.github/actions/github-composite-env@debug-github-action-compose-env
        env:
          STEP_COMPOSITE: null
          STEP_1: null
          STEP_2: null
          STEP_3: null
          STEP_4: null
          STEP_5: null
          STEP_6: null
        with:
          step: 2
      - name: check
        if: always()
        shell: bash
        run: |
          exec 2>&1
          set -x
          STEP=1
          RESULT=0
          VAR="STEP_${STEP}_COMPOSITE_1"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_2"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_3"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_4"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_5"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_6"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))

          VAR="STEP_${STEP}_COMPOSITE"
          test "${!VAR}" = "6" || RESULT=$((RESULT+1))

          VAR="STEP_1"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_2"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_3"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_4"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_5"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_6"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))

          VAR="STEP_COMPOSITE"
          test "${!VAR}" = "${STEP}6" || RESULT=$((RESULT+1))

          exit $RESULT

  local:
    timeout-minutes: 30
    name: local
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: step1
        uses: ./.github/actions/github-composite-env
        with:
          step: 1
      - name: step2
        uses: ./.github/actions/github-composite-env
        with:
          step: 2
      - name: check
        if: always()
        shell: bash
        run: |
          exec 2>&1
          set -x
          STEP=2
          RESULT=0
          VAR="STEP_${STEP}_COMPOSITE_1"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_2"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_3"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_4"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_5"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))
          VAR="STEP_${STEP}_COMPOSITE_6"
          test "${!VAR}" = "true" || RESULT=$((RESULT+1))

          VAR="STEP_${STEP}_COMPOSITE"
          test "${!VAR}" = "6" || RESULT=$((RESULT+1))

          VAR="STEP_1"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_2"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_3"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_4"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_5"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))
          VAR="STEP_6"
          test "${!VAR}" = "${STEP}" || RESULT=$((RESULT+1))

          VAR="STEP_COMPOSITE"
          test "${!VAR}" = "${STEP}6" || RESULT=$((RESULT+1))

          exit $RESULT
