name: debug
'on':
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: null
concurrency:
  group: 'main'
  cancel-in-progress: true
jobs:
  main:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        'runs-on':
          - x64
          - ARM64
    name: self-hosted-'${{ matrix.runs-on }}'
    runs-on: [self-hosted, '${{ matrix.runs-on }}']
    steps:
      - uses: ysoftwareab/yplatform/.github/actions/debug@master
        with:
          file: debug.new.txt
      - id: cache-keys
        shell: bash
        run: echo ::set-output name=yyyymm::$(/bin/date -u "+%Y%m")
      - id: cache
        uses: actions/cache@v3
        with:
          path: |
            debug.txt
          key: self-hosted-${{ matrix.runs-on }}-output-${{ steps.cache-keys.output.yyyymm }}-v1
          'restore-keys': |
            self-hosted-${{ matrix.runs-on }}-output-${{ steps.cache-keys.output.yyyymm }}-v1
      - if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        # TODO nice if one can ignore values that are ever changing, and report only relevant diffs
        run: |
          diff --unified=1000000 debug.txt debug.new.txt || true
      - shell: bash
        run: |
          mv debug.new.txt debug.txt
