#!/usr/bin/env bash
set -euo pipefail

GIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUPPORT_FIRECLOUD_DIR="$(cd "${GIT_ROOT}/support-firecloud" && pwd)"

SRC_FILE=.github/workflows.src/main.yml

# ci
ENVSUBST_WSLENV=CI:V
# support-firecloud
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:SF_LOG_BOOTSTRAP:SF_PRINTENV_BOOTSTRAP
# github
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GH_TOKEN:GH_USERNAME
# transcrypt
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:TRANSCRYPT_PASSWORD
# slack
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:SLACK_WEBHOOK:SLACK_CHANNEL:CI_STATUS
# github # hardcoded list
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GITHUB_ACTION:GITHUB_ACTIONS:GITHUB_ACTOR:GITHUB_API_URL:GITHUB_BASE_REF
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GITHUB_ENV:GITHUB_EVENT_NAME:GITHUB_EVENT_PATH/p:GITHUB_GRAPHQL_URL:GITHUB_HEAD_REF
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GITHUB_JOB:GITHUB_MATRIX_OS:GITHUB_PATH:GITHUB_REF:GITHUB_REPOSITORY
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GITHUB_REPOSITORY_OWNER:GITHUB_RETENTION_DAYS:GITHUB_RUN_ID:GITHUB_RUN_NUMBER
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:GITHUB_SERVER_URL:GITHUB_SHA:GITHUB_WORKFLOW:GITHUB_WORKSPACE/p
# custom
ENVSUBST_WSLENV=${ENVSUBST_WSLENV}:SF_CI_BREW_INSTALL
export ENVSUBST_WSLENV

echo "# WARNING: DO NOT EDIT. AUTO-GENERATED CODE (${SRC_FILE})"
cat ${GIT_ROOT}/${SRC_FILE} | \
  envsubst "$(printenv | grep "^ENVSUBST_" | sed "s/=.*//g" | sed "s/^/\${/g" | sed "s/\$/}/g")" | \
  ${SUPPORT_FIRECLOUD_DIR}/bin/yaml-expand
