#!/usr/bin/env bash

function on_exit() {
    # shellcheck disable=SC2181
    [[ "$?" != "0" ]] || return 0

    echo "[ERR ] pre-push hook failed."
    echo "[INFO] If you want ignore the hook and push anyway, use 'git push --no-verify ...'."
}

trap on_exit EXIT

SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../support-firecloud" && pwd)"
source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh

GIT_MODIFIED_FILES="$(git diff --name-only)"
[[ -z "${GIT_MODIFIED_FILES}" ]] || {
    echo_warn "The files/submodules below are modified and unstaged,"
    echo_warn "so the push might fail because of unstaged changes, not related to actual commits."
    echo "${GIT_MODIFIED_FILES}"
}

export GIT_HOOK_STDIN="$(cat /dev/stdin)"
export GIT_HOOK_ARGS="$@"

make .git/hooks/pre-push/run
